# quick and dirty on a friday evening

- hosts: cumulus-nodes
#- hosts: leaf12
  name: startup
  become: yes
  gather_facts: no
  tasks:
    - name: create initial startup.yaml
      copy:
        src: /home/ubuntu/ON-17/step-01/{{ inventory_hostname }}.yaml
        dest: /etc/nvue.d/startup.yaml
    # aktivieren
    - name: apply
      shell:  nv config apply startup -y
