# quick and dirty on a friday evening

- hosts: switches
  name: startup
  become: yes
  gather_facts: no
  tasks:
    - name: copy startup.yaml
      copy:
        src: /home/cumulus/ON-17/step-01/{{ inventory_hostname }}.yaml
        dest: /etc/nvue.d/startup.yaml
    # aktivieren
    - name: activate changes for leaf
      shell:  nv config apply startup -y
