# quick and dirty over the weekend

- hosts: cumulus-nodes
  name: cleanup
  become: yes
  gather_facts: no
  tasks:
    - name: setting the host names
      copy:
        src: /home/ubuntu/ON-17/step-01/{{ inventory_hostname }}.yaml
        dest: /etc/nvue.d/startup.yaml
    # aktivieren
    - name: apply
      shell:  nv config apply startup -y
